apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argo-cd-prod
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system
  source:
    path: metrics-server
    repoURL: 'https://github.com/3letteragency/hq-default-apps'
    targetRevision: HEAD
