apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespaces: argo-cd-prod
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: metrics-server
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
